<?php

namespace Database\Factories;

use App\Models\UnitKerja;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\UnitKerja>
 */
class UnitKerjaFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            $data = [
                    ['11', '1100', 'BPS PROVINSI ACEH'],
                    ['11', '1101', 'BPS KABUPATEN SIMEULUE'],
                    ['11', '1102', 'BPS KABUPATEN ACEH SINGKIL'],
                    ['11', '1103', 'BPS KABUPATEN ACEH SELATAN'],
                    ['11', '1104', 'BPS KABUPATEN ACEH TENGGARA'],
                    ['11', '1105', 'BPS KABUPATEN ACEH TIMUR'],
                    ['11', '1106', 'BPS KABUPATEN ACEH TENGAH'],
                    ['11', '1107', 'BPS KABUPATEN ACEH BARAT'],
                    ['11', '1108', 'BPS KABUPATEN ACEH BESAR'],
                    ['11', '1109', 'BPS KABUPATEN PIDIE'],
                    ['11', '1110', 'BPS KABUPATEN BIREUEN'],
                    ['11', '1111', 'BPS KABUPATEN ACEH UTARA'],
                    ['11', '1112', 'BPS KABUPATEN ACEH BARAT DAYA'],
                    ['11', '1113', 'BPS KABUPATEN GAYO LUES'],
                    ['11', '1114', 'BPS KABUPATEN ACEH TAMIANG'],
                    ['11', '1115', 'BPS KABUPATEN NAGAN RAYA'],
                    ['11', '1116', 'BPS KABUPATEN ACEH JAYA'],
                    ['11', '1117', 'BPS KABUPATEN BENER MERIAH'],
                    ['11', '1118', 'BPS KABUPATEN PIDIE JAYA'],
                    ['11', '1171', 'BPS KOTA BANDA ACEH'],
                    ['11', '1172', 'BPS KOTA SABANG'],
                    ['11', '1173', 'BPS KOTA LANGSA'],
                    ['11', '1174', 'BPS KOTA LHOKSEUMAWE'],
                    ['11', '1175', 'BPS KOTA SUBULUSSALAM'],
                    ['12', '1200', 'BPS PROVINSI SUMATERA UTARA'],
                    ['12', '1201', 'BPS KABUPATEN NIAS'],
                    ['12', '1202', 'BPS KABUPATEN MANDAILING NATAL'],
                    ['12', '1203', 'BPS KABUPATEN TAPANULI SELATAN'],
                    ['12', '1204', 'BPS KABUPATEN TAPANULI TENGAH'],
                    ['12', '1205', 'BPS KABUPATEN TAPANULI UTARA'],
                    ['12', '1206', 'BPS KABUPATEN TOBA SAMOSIR'],
                    ['12', '1207', 'BPS KABUPATEN LABUHAN BATU'],
                    ['12', '1208', 'BPS KABUPATEN ASAHAN'],
                    ['12', '1209', 'BPS KABUPATEN SIMALUNGUN'],
                    ['12', '1210', 'BPS KABUPATEN DAIRI'],
                    ['12', '1211', 'BPS KABUPATEN KARO'],
                    ['12', '1212', 'BPS KABUPATEN DELI SERDANG'],
                    ['12', '1213', 'BPS KABUPATEN LANGKAT'],
                    ['12', '1214', 'BPS KABUPATEN NIAS SELATAN'],
                    ['12', '1215', 'BPS KABUPATEN HUMBANG HASUNDUTAN'],
                    ['12', '1216', 'BPS KABUPATEN PAKPAK BHARAT'],
                    ['12', '1217', 'BPS KABUPATEN SAMOSIR'],
                    ['12', '1218', 'BPS KABUPATEN SERDANG BEDAGAI'],
                    ['12', '1219', 'BPS KABUPATEN BATU BARA'],
                    ['12', '1220', 'BPS KABUPATEN PADANG LAWAS UTARA'],
                    ['12', '1221', 'BPS KABUPATEN PADANG LAWAS'],
                    ['12', '1222', 'BPS KABUPATEN LABUHAN BATU SELATAN'],
                    ['12', '1223', 'BPS KABUPATEN LABUHAN BATU UTARA'],
                    ['12', '1271', 'BPS KOTA SIBOLGA'],
                    ['12', '1272', 'BPS KOTA TANJUNG BALAI'],
                    ['12', '1273', 'BPS KOTA PEMATANG SIANTAR'],
                    ['12', '1274', 'BPS KOTA TEBING TINGGI'],
                    ['12', '1275', 'BPS KOTA MEDAN'],
                    ['12', '1276', 'BPS KOTA BINJAI'],
                    ['12', '1277', 'BPS KOTA PADANGSIDIMPUAN'],
                    ['12', '1278', 'BPS KOTA GUNUNGSITOLI'],
                    ['13', '1300', 'BPS PROVINSI SUMATERA BARAT'],
                    ['13', '1301', 'BPS KABUPATEN KEPULAUAN MENTAWAI'],
                    ['13', '1302', 'BPS KABUPATEN PESISIR SELATAN'],
                    ['13', '1303', 'BPS KABUPATEN SOLOK'],
                    ['13', '1304', 'BPS KABUPATEN SIJUNJUNG'],
                    ['13', '1305', 'BPS KABUPATEN TANAH DATAR'],
                    ['13', '1306', 'BPS KABUPATEN PADANG PARIAMAN'],
                    ['13', '1307', 'BPS KABUPATEN AGAM'],
                    ['13', '1308', 'BPS KABUPATEN LIMA PULUH KOTA'],
                    ['13', '1309', 'BPS KABUPATEN PASAMAN'],
                    ['13', '1310', 'BPS KABUPATEN SOLOK SELATAN'],
                    ['13', '1311', 'BPS KABUPATEN DHARMASRAYA'],
                    ['13', '1312', 'BPS KABUPATEN PASAMAN BARAT'],
                    ['13', '1371', 'BPS KOTA PADANG'],
                    ['13', '1372', 'BPS KOTA SOLOK'],
                    ['13', '1373', 'BPS KOTA SAWAH LUNTO'],
                    ['13', '1374', 'BPS KOTA PADANG PANJANG'],
                    ['13', '1375', 'BPS KOTA BUKITTINGGI'],
                    ['13', '1376', 'BPS KOTA PAYAKUMBUH'],
                    ['13', '1377', 'BPS KOTA PARIAMAN'],
                    ['14', '1400', 'BPS PROVINSI RIAU'],
                    ['14', '1401', 'BPS KABUPATEN KUANTAN SINGINGI'],
                    ['14', '1402', 'BPS INDRAGIRI HULU'],
                    ['14', '1403', 'BPS KABUPATEN INDRAGIRI HILIR'],
                    ['14', '1404', 'BPS KABUPATEN PELALAWAN'],
                    ['14', '1405', 'BPS KABUPATEN SIAK'],
                    ['14', '1406', 'BPS KABUPATEN KAMPAR'],
                    ['14', '1407', 'BPS KABUPATEN ROKAN HULU'],
                    ['14', '1408', 'BPS KABUPATEN BENGKALIS'],
                    ['14', '1409', 'BPS KABUPATEN ROKAN HILIR'],
                    ['14', '1410', 'BPS KABUPATEN KEPULAUAN MERANTI'],
                    ['14', '1471', 'BPS KOTA PEKANBARU'],
                    ['14', '1473', 'BPS KOTA DUMAI'],
                    ['15', '1500', 'BPS PROVINSI JAMBI'],
                    ['15', '1501', 'BPS KABUPATEN KERINCI'],
                    ['15', '1502', 'BPS KABUPATEN MERANGIN'],
                    ['15', '1503', 'BPS KABUPATEN SAROLANGUN'],
                    ['15', '1504', 'BPS KABUPATEN BATANG HARI'],
                    ['15', '1505', 'BPS KABUPATEN MUARO JAMBI'],
                    ['15', '1506', 'BPS KABUPATEN TANJUNG JABUNG TIMUR'],
                    ['15', '1507', 'BPS KABUPATEN TANJUNG JABUNG BARAT'],
                    ['15', '1508', 'BPS KABUPATEN TEBO'],
                    ['15', '1509', 'BPS KABUPATEN BUNGO'],
                    ['15', '1571', 'BPS KOTA JAMBI'],
                    ['15', '1572', 'BPS KOTA SUNGAI PENUH'],
                    ['16', '1600', 'BPS PROVINSI SUMATERA SELATAN'],
                    ['16', '1601', 'BPS KABUPATEN OGAN KOMERING ULU'],
                    ['16', '1602', 'BPS KABUPATEN OGAN KOMERING ILIR'],
                    ['16', '1603', 'BPS KABUPATEN MUARA ENIM'],
                    ['16', '1604', 'BPS KABUPATEN LAHAT'],
                    ['16', '1605', 'BPS KABUPATEN MUSI RAWAS'],
                    ['16', '1606', 'BPS KABUPATEN MUSI BANYUASIN'],
                    ['16', '1607', 'BPS KABUPATEN BANYU ASIN'],
                    ['16', '1608', 'BPS KABUPATEN OGAN KOMERING ULU SELATAN'],
                    ['16', '1609', 'BPS KABUPATEN OGAN KOMERING ULU TIMUR'],
                    ['16', '1610', 'BPS KABUPATEN OGAN ILIR'],
                    ['16', '1611', 'BPS KABUPATEN EMPAT LAWANG'],
                    ['16', '1671', 'BPS KOTA PALEMBANG'],
                    ['16', '1672', 'BPS KOTA PRABUMULIH'],
                    ['16', '1673', 'BPS KOTA PAGAR ALAM'],
                    ['16', '1674', 'BPS KOTA LUBUKLINGGAU'],
                    ['17', '1700', 'BPS PROVINSI BENGKULU'],
                    ['17', '1701', 'BPS KABUPATEN BENGKULU SELATAN'],
                    ['17', '1702', 'BPS KABUPATEN REJANG LEBONG'],
                    ['17', '1703', 'BPS KABUPATEN BENGKULU UTARA'],
                    ['17', '1704', 'BPS KABUPATEN KAUR'],
                    ['17', '1705', 'BPS KABUPATEN SELUMA'],
                    ['17', '1706', 'BPS KABUPATEN MUKOMUKO'],
                    ['17', '1707', 'BPS KABUPATEN LEBONG'],
                    ['17', '1708', 'BPS KABUPATEN KEPAHIANG'],
                    ['17', '1709', 'BPS KABUPATEN BENGKULU TENGAH'],
                    ['17', '1771', 'BPS KOTA BENGKULU'],
                    ['18', '1800', 'BPS PROVINSI LAMPUNG'],
                    ['18', '1801', 'BPS KABUPATEN LAMPUNG BARAT'],
                    ['18', '1802', 'BPS KABUPATEN TANGGAMUS'],
                    ['18', '1803', 'BPS KABUPATEN LAMPUNG SELATAN'],
                    ['18', '1804', 'BPS KABUPATEN LAMPUNG TIMUR'],
                    ['18', '1805', 'BPS KABUPATEN LAMPUNG TENGAH'],
                    ['18', '1806', 'BPS KABUPATEN LAMPUNG UTARA'],
                    ['18', '1807', 'BPS KABUPATEN WAY KANAN'],
                    ['18', '1808', 'BPS KABUPATEN TULANGBAWANG'],
                    ['18', '1809', 'BPS KABUPATEN PESAWARAN'],
                    ['18', '1810', 'BPS KABUPATEN PRINGSEWU'],
                    ['18', '1811', 'BPS KABUPATEN MESUJI'],
                    ['18', '1812', 'BPS KABUPATEN TULANG BAWANG BARAT'],
                    ['18', '1871', 'BPS KOTA BANDAR LAMPUNG'],
                    ['18', '1872', 'BPS KOTA METRO'],
                    ['19', '1900', 'BPS PROVINSI KEPULAUAN BANGKA BELITUNG'],
                    ['19', '1901', 'BPS KABUPATEN BANGKA'],
                    ['19', '1902', 'BPS KABUPATEN BELITUNG'],
                    ['19', '1903', 'BPS KABUPATEN BANGKA BARAT'],
                    ['19', '1904', 'BPS KABUPATEN BANGKA TENGAH'],
                    ['19', '1905', 'BPS KABUPATEN BANGKA SELATAN'],
                    ['19', '1906', 'BPS KABUPATEN BELITUNG TIMUR'],
                    ['19', '1971', 'BPS KOTA PANGKAL PINANG'],
                    ['21', '2100', 'BPS PROVINSI KEPULAUAN RIAU'],
                    ['21', '2101', 'BPS KABUPATEN KARIMUN'],
                    ['21', '2102', 'BPS KABUPATEN BINTAN'],
                    ['21', '2103', 'BPS KABUPATEN NATUNA'],
                    ['21', '2104', 'BPS KABUPATEN LINGGA'],
                    ['21', '2105', 'BPS KABUPATEN KEPULAUAN ANAMBAS'],
                    ['21', '2171', 'BPS KOTA BATAM'],
                    ['21', '2172', 'BPS KOTA TANJUNG PINANG'],
                    ['31', '3100', 'BPS PROVINSI DKI JAKARTA'],
                    ['31', '3101', 'BPS KABUPATEN KEPULAUAN SERIBU'],
                    ['31', '3171', 'BPS KOTA JAKARTA SELATAN'],
                    ['31', '3172', 'BPS KOTA JAKARTA TIMUR'],
                    ['31', '3173', 'BPS KOTA JAKARTA PUSAT'],
                    ['31', '3174', 'BPS KOTA JAKARTA BARAT'],
                    ['31', '3175', 'BPS KOTA JAKARTA UTARA'],
                    ['32', '3200', 'BPS PROVINSI JAWA BARAT'],
                    ['32', '3201', 'BPS KABUPATEN BOGOR'],
                    ['32', '3202', 'BPS KABUPATEN SUKABUMI'],
                    ['32', '3203', 'BPS KABUPATEN CIANJUR'],
                    ['32', '3204', 'BPS KABUPATEN BANDUNG'],
                    ['32', '3205', 'BPS KABUPATEN GARUT'],
                    ['32', '3206', 'BPS KABUPATEN TASIKMALAYA'],
                    ['32', '3207', 'BPS KABUPATEN CIAMIS'],
                    ['32', '3208', 'BPS KABUPATEN KUNINGAN'],
                    ['32', '3209', 'BPS KABUPATEN CIREBON'],
                    ['32', '3210', 'BPS KABUPATEN MAJALENGKA'],
                    ['32', '3211', 'BPS KABUPATEN SUMEDANG'],
                    ['32', '3212', 'BPS KABUPATEN INDRAMAYU'],
                    ['32', '3213', 'BPS KABUPATEN SUBANG'],
                    ['32', '3214', 'BPS KABUPATEN PURWAKARTA'],
                    ['32', '3215', 'BPS KABUPATEN KARAWANG'],
                    ['32', '3216', 'BPS KABUPATEN BEKASI'],
                    ['32', '3217', 'BPS KABUPATEN BANDUNG BARAT'],
                    ['32', '3271', 'BPS KOTA BOGOR'],
                    ['32', '3272', 'BPS KOTA SUKABUMI'],
                    ['32', '3273', 'BPS KOTA BANDUNG'],
                    ['32', '3274', 'BPS KOTA CIREBON'],
                    ['32', '3275', 'BPS KOTA BEKASI'],
                    ['32', '3276', 'BPS KOTA DEPOK'],
                    ['32', '3277', 'BPS KOTA CIMAHI'],
                    ['32', '3278', 'BPS KOTA TASIKMALAYA'],
                    ['32', '3279', 'BPS KOTA BANJAR'],
                    ['33', '3300', 'BPS PROVINSI JAWA TENGAH'],
                    ['33', '3301', 'BPS KABUPATEN CILACAP'],
                    ['33', '3302', 'BPS KABUPATEN BANYUMAS'],
                    ['33', '3303', 'BPS KABUPATEN PURBALINGGA'],
                    ['33', '3304', 'BPS KABUPATEN BANJARNEGARA'],
                    ['33', '3305', 'BPS KABUPATEN KEBUMEN'],
                    ['33', '3306', 'BPS KABUPATEN PURWOREJO'],
                    ['33', '3307', 'BPS KABUPATEN WONOSOBO'],
                    ['33', '3308', 'BPS KABUPATEN MAGELANG'],
                    ['33', '3309', 'BPS KABUPATEN BOYOLALI'],
                    ['33', '3310', 'BPS KABUPATEN KLATEN'],
                    ['33', '3311', 'BPS KABUPATEN SUKOHARJO'],
                    ['33', '3312', 'BPS KABUPATEN WONOGIRI'],
                    ['33', '3313', 'BPS KABUPATEN KARANGANYAR'],
                    ['33', '3314', 'BPS KABUPATEN SRAGEN'],
                    ['33', '3315', 'BPS KABUPATEN GROBOGAN'],
                    ['33', '3316', 'BPS KABUPATEN BLORA'],
                    ['33', '3317', 'BPS KABUPATEN REMBANG'],
                    ['33', '3318', 'BPS KABUPATEN PATI'],
                    ['33', '3319', 'BPS KABUPATEN KUDUS'],
                    ['33', '3320', 'BPS KABUPATEN JEPARA'],
                    ['33', '3321', 'BPS KABUPATEN DEMAK'],
                    ['33', '3322', 'BPS KABUPATEN SEMARANG'],
                    ['33', '3323', 'BPS KABUPATEN TEMANGGUNG'],
                    ['33', '3324', 'BPS KABUPATEN KENDAL'],
                    ['33', '3325', 'BPS KABUPATEN BATANG'],
                    ['33', '3326', 'BPS KABUPATEN PEKALONGAN'],
                    ['33', '3327', 'BPS KABUPATEN PEMALANG'],
                    ['33', '3328', 'BPS KABUPATEN TEGAL'],
                    ['33', '3329', 'BPS KABUPATEN BREBES'],
                    ['33', '3371', 'BPS KOTA MAGELANG'],
                    ['33', '3372', 'BPS KOTA SURAKARTA'],
                    ['33', '3373', 'BPS KOTA SALATIGA'],
                    ['33', '3374', 'BPS KOTA SEMARANG'],
                    ['33', '3375', 'BPS KOTA PEKALONGAN'],
                    ['33', '3376', 'BPS KOTA TEGAL'],
                    ['34', '3400', 'BPS PROVINSI DI YOGYAKARTA'],
                    ['34', '3401', 'BPS KABUPATEN KULON PROGO'],
                    ['34', '3402', 'BPS KABUPATEN BANTUL'],
                    ['34', '3403', 'BPS KABUPATEN GUNUNG KIDUL'],
                    ['34', '3404', 'BPS KABUPATEN SLEMAN'],
                    ['34', '3471', 'BPS KOTA YOGYAKARTA'],
                    ['35', '3500', 'BPS PROVINSI JAWA TIMUR'],
                    ['35', '3501', 'BPS KABUPATEN PACITAN'],
                    ['35', '3502', 'BPS KABUPATEN PONOROGO'],
                    ['35', '3503', 'BPS KABUPATEN TRENGGALEK'],
                    ['35', '3504', 'BPS KABUPATEN TULUNGAGUNG'],
                    ['35', '3505', 'BPS KABUPATEN BLITAR'],
                    ['35', '3506', 'BPS KABUPATEN KEDIRI'],
                    ['35', '3507', 'BPS KABUPATEN MALANG'],
                    ['35', '3508', 'BPS KABUPATEN LUMAJANG'],
                    ['35', '3509', 'BPS KABUPATEN JEMBER'],
                    ['35', '3510', 'BPS KABUPATEN BANYUWANGI'],
                    ['35', '3511', 'BPS KABUPATEN BONDOWOSO'],
                    ['35', '3512', 'BPS KABUPATEN SITUBONDO'],
                    ['35', '3513', 'BPS KABUPATEN PROBOLINGGO'],
                    ['35', '3514', 'BPS KABUPATEN PASURUAN'],
                    ['35', '3515', 'BPS KABUPATEN SIDOARJO'],
                    ['35', '3516', 'BPS KABUPATEN MOJOKERTO'],
                    ['35', '3517', 'BPS KABUPATEN JOMBANG'],
                    ['35', '3518', 'BPS KABUPATEN NGANJUK'],
                    ['35', '3519', 'BPS KABUPATEN MADIUN'],
                    ['35', '3520', 'BPS KABUPATEN MAGETAN'],
                    ['35', '3521', 'BPS KABUPATEN NGAWI'],
                    ['35', '3522', 'BPS KABUPATEN BOJONEGORO'],
                    ['35', '3523', 'BPS KABUPATEN TUBAN'],
                    ['35', '3524', 'BPS KABUPATEN LAMONGAN'],
                    ['35', '3525', 'BPS KABUPATEN GRESIK'],
                    ['35', '3526', 'BPS KABUPATEN BANGKALAN'],
                    ['35', '3527', 'BPS KABUPATEN SAMPANG'],
                    ['35', '3528', 'BPS KABUPATEN PAMEKASAN'],
                    ['35', '3529', 'BPS KABUPATEN SUMENEP'],
                    ['35', '3571', 'BPS KOTA KEDIRI'],
                    ['35', '3572', 'BPS KOTA BLITAR'],
                    ['35', '3573', 'BPS KOTA MALANG'],
                    ['35', '3574', 'BPS KOTA PROBOLINGGO'],
                    ['35', '3575', 'BPS KOTA PASURUAN'],
                    ['35', '3576', 'BPS KOTA MOJOKERTO'],
                    ['35', '3577', 'BPS KOTA MADIUN'],
                    ['35', '3578', 'BPS KOTA SURABAYA'],
                    ['35', '3579', 'BPS KOTA BATU'],
                    ['36', '3600', 'BPS PROVINSI BANTEN'],
                    ['36', '3601', 'BPS KABUPATEN PANDEGLANG'],
                    ['36', '3602', 'BPS KABUPATEN LEBAK'],
                    ['36', '3603', 'BPS KABUPATEN TANGERANG'],
                    ['36', '3604', 'BPS KABUPATEN SERANG'],
                    ['36', '3671', 'BPS KOTA TANGERANG'],
                    ['36', '3672', 'BPS KOTA CILEGON'],
                    ['36', '3673', 'BPS KOTA SERANG'],
                    ['36', '3674', 'BPS KOTA TANGERANG SELATAN'],
                    ['51', '5100', 'BPS PROVINSI BALI'],
                    ['51', '5101', 'BPS KABUPATEN JEMBRANA'],
                    ['51', '5102', 'BPS KABUPATEN TABANAN'],
                    ['51', '5103', 'BPS KABUPATEN BADUNG'],
                    ['51', '5104', 'BPS KABUPATEN GIANYAR'],
                    ['51', '5105', 'BPS KABUPATEN KLUNGKUNG'],
                    ['51', '5106', 'BPS KABUPATEN BANGLI'],
                    ['51', '5107', 'BPS KABUPATEN KARANG ASEM'],
                    ['51', '5108', 'BPS KABUPATEN BULELENG'],
                    ['51', '5171', 'BPS KOTA DENPASAR'],
                    ['52', '5200', 'BPS PROVINSI NUSA TENGGARA BARAT'],
                    ['52', '5201', 'BPS KABUPATEN LOMBOK BARAT'],
                    ['52', '5202', 'BPS KABUPATEN LOMBOK TENGAH'],
                    ['52', '5203', 'BPS KABUPATEN LOMBOK TIMUR'],
                    ['52', '5204', 'BPS KABUPATEN SUMBAWA'],
                    ['52', '5205', 'BPS KABUPATEN DOMPU'],
                    ['52', '5206', 'BPS KABUPATEN BIMA'],
                    ['52', '5207', 'BPS KABUPATEN SUMBAWA BARAT'],
                    ['52', '5208', 'BPS KABUPATEN LOMBOK UTARA'],
                    ['52', '5271', 'BPS KOTA MATARAM'],
                    ['52', '5272', 'BPS KOTA BIMA'],
                    ['53', '5300', 'BPS PROVINSI NUSA TENGGARA TIMUR'],
                    ['53', '5301', 'BPS KABUPATEN SUMBA BARAT'],
                    ['53', '5302', 'BPS KABUPATEN SUMBA TIMUR'],
                    ['53', '5303', 'BPS KABUPATEN KUPANG'],
                    ['53', '5304', 'BPS KABUPATEN TIMOR TENGAH SELATAN'],
                    ['53', '5305', 'BPS KABUPATEN TIMOR TENGAH UTARA'],
                    ['53', '5306', 'BPS KABUPATEN BELU'],
                    ['53', '5307', 'BPS KABUPATEN ALOR'],
                    ['53', '5308', 'BPS KABUPATEN LEMBATA'],
                    ['53', '5309', 'BPS KABUPATEN FLORES TIMUR'],
                    ['53', '5310', 'BPS KABUPATEN SIKKA'],
                    ['53', '5311', 'BPS KABUPATEN ENDE'],
                    ['53', '5312', 'BPS KABUPATEN NGADA'],
                    ['53', '5313', 'BPS KABUPATEN MANGGARAI'],
                    ['53', '5314', 'BPS KABUPATEN ROTE NDAO'],
                    ['53', '5315', 'BPS KABUPATEN MANGGARAI BARAT'],
                    ['53', '5317', 'BPS KABUPATEN SUMBA BARAT DAYA'],
                    ['53', '5318', 'BPS KABUPATEN NAGEKEO'],
                    ['53', '5319', 'BPS KABUPATEN MANGGARAI TIMUR'],
                    ['53', '5371', 'BPS KOTA KUPANG'],
                    ['61', '6100', 'BPS PROVINSI KALIMANTAN BARAT'],
                    ['61', '6101', 'BPS KABUPATEN SAMBAS'],
                    ['61', '6102', 'BPS KABUPATEN BENGKAYANG'],
                    ['61', '6103', 'BPS KABUPATEN LANDAK'],
                    ['61', '6104', 'BPS KABUPATEN PONTIANAK/MEMPAWAH'],
                    ['61', '6105', 'BPS KABUPATEN SANGGAU'],
                    ['61', '6106', 'BPS KABUPATEN KETAPANG'],
                    ['61', '6107', 'BPS KABUPATEN SINTANG'],
                    ['61', '6108', 'BPS KABUPATEN KAPUAS HULU'],
                    ['61', '6109', 'BPS KABUPATEN SEKADAU'],
                    ['61', '6110', 'BPS KABUPATEN MELAWI'],
                    ['61', '6111', 'BPS KABUPATEN KAYONG UTARA'],
                    ['61', '6112', 'BPS KABUPATEN KUBU RAYA'],
                    ['61', '6171', 'BPS KOTA PONTIANAK'],
                    ['61', '6172', 'BPS KOTA SINGKAWANG'],
                    ['62', '6200', 'BPS PROVINSI KALIMANTAN TENGAH'],
                    ['62', '6201', 'BPS KABUPATEN KOTAWARINGIN BARAT'],
                    ['62', '6202', 'BPS KABUPATEN KOTAWARINGIN TIMUR'],
                    ['62', '6203', 'BPS KABUPATEN KAPUAS'],
                    ['62', '6204', 'BPS KABUPATEN BARITO SELATAN'],
                    ['62', '6205', 'BPS KABUPATEN BARITO UTARA'],
                    ['62', '6206', 'BPS KABUPATEN SUKAMARA'],
                    ['62', '6207', 'BPS KABUPATEN LAMANDAU'],
                    ['62', '6208', 'BPS KABUPATEN SERUYAN'],
                    ['62', '6209', 'BPS KABUPATEN KATINGAN'],
                    ['62', '6210', 'BPS KABUPATEN PULANG PISAU'],
                    ['62', '6211', 'BPS KABUPATEN GUNUNG MAS'],
                    ['62', '6212', 'BPS KABUPATEN BARITO TIMUR'],
                    ['62', '6213', 'BPS KABUPATEN MURUNG RAYA'],
                    ['62', '6271', 'BPS KOTA PALANGKA RAYA'],
                    ['63', '6300', 'BPS PROVINSI KALIMANTAN SELATAN'],
                    ['63', '6301', 'BPS KABUPATEN TANAH LAUT'],
                    ['63', '6302', 'BPS KABUPATEN KOTA BARU'],
                    ['63', '6303', 'BPS KABUPATEN BANJAR'],
                    ['63', '6304', 'BPS KABUPATEN BARITO KUALA'],
                    ['63', '6305', 'BPS KABUPATEN TAPIN'],
                    ['63', '6306', 'BPS KABUPATEN HULU SUNGAI SELATAN'],
                    ['63', '6307', 'BPS KABUPATEN HULU SUNGAI TENGAH'],
                    ['63', '6308', 'BPS KABUPATEN HULU SUNGAI UTARA'],
                    ['63', '6309', 'BPS KABUPATEN TABALONG'],
                    ['63', '6310', 'BPS KABUPATEN TANAH BUMBU'],
                    ['63', '6311', 'BPS KABUPATEN BALANGAN'],
                    ['63', '6371', 'BPS KOTA BANJARMASIN'],
                    ['63', '6372', 'BPS KOTA BANJAR BARU'],
                    ['64', '6400', 'BPS PROVINSI KALIMANTAN TIMUR'],
                    ['64', '6401', 'BPS KABUPATEN PASER'],
                    ['64', '6402', 'BPS KABUPATEN KUTAI BARAT'],
                    ['64', '6403', 'BPS KABUPATEN KUTAI KARTANEGARA'],
                    ['64', '6404', 'BPS KABUPATEN KUTAI TIMUR'],
                    ['64', '6405', 'BPS KABUPATEN BERAU'],
                    ['64', '6409', 'BPS KABUPATEN PENAJAM PASER UTARA'],
                    ['64', '6471', 'BPS KOTA BALIKPAPAN'],
                    ['64', '6472', 'BPS KOTA SAMARINDA'],
                    ['64', '6474', 'BPS KOTA BONTANG'],
                    ['65', '6500', 'BPS PROVINSI KALIMANTAN UTARA'],
                    ['65', '6501', 'BPS KABUPATEN MALINAU'],
                    ['65', '6502', 'BPS KABUPATEN BULUNGAN'],
                    ['65', '6503', 'BPS KABUPATEN TANA TIDUNG'],
                    ['65', '6504', 'BPS KABUPATEN NUNUKAN'],
                    ['65', '6571', 'BPS KOTA TARAKAN'],
                    ['71', '7100', 'BPS PROVINSI SULAWESI UTARA'],
                    ['71', '7101', 'BPS KABUPATEN BOLAANG MONGONDOW'],
                    ['71', '7102', 'BPS KABUPATEN MINAHASA'],
                    ['71', '7103', 'BPS KABUPATEN KEPULAUAN SANGIHE'],
                    ['71', '7104', 'BPS KABUPATEN KEPULAUAN TALAUD'],
                    ['71', '7105', 'BPS KABUPATEN MINAHASA SELATAN'],
                    ['71', '7106', 'BPS KABUPATEN MINAHASA UTARA'],
                    ['71', '7107', 'BPS KABUPATEN BOLAANG MONGONDOW UTARA'],
                    ['71', '7108', 'BPS KABUPATEN SIAU TAGULANDANG BIARO'],
                    ['71', '7171', 'BPS KOTA MANADO'],
                    ['71', '7172', 'BPS KOTA BITUNG'],
                    ['71', '7173', 'BPS KOTA TOMOHON'],
                    ['71', '7174', 'BPS KOTA KOTAMOBAGU'],
                    ['72', '7200', 'BPS PROVINSI SULAWESI TENGAH'],
                    ['72', '7201', 'BPS KABUPATEN BANGGAI KEPULAUAN'],
                    ['72', '7202', 'BPS KABUPATEN BANGGAI'],
                    ['72', '7203', 'BPS KABUPATEN MOROWALI'],
                    ['72', '7204', 'BPS KABUPATEN POSO'],
                    ['72', '7205', 'BPS KABUPATEN DONGGALA'],
                    ['72', '7206', 'BPS KABUPATEN TOLI-TOLI'],
                    ['72', '7207', 'BPS KABUPATEN BUOL'],
                    ['72', '7208', 'BPS KABUPATEN PARIGI MOUTONG'],
                    ['72', '7209', 'BPS KABUPATEN TOJO UNA-UNA'],
                    ['72', '7210', 'BPS KABUPATEN SIGI'],
                    ['72', '7271', 'BPS KOTA PALU'],
                    ['73', '7300', 'BPS PROVINSI SULAWESI SELATAN'],
                    ['73', '7301', 'BPS KABUPATEN KEPULAUAN SELAYAR'],
                    ['73', '7302', 'BPS KABUPATEN BULUKUMBA'],
                    ['73', '7303', 'BPS KABUPATEN BANTAENG'],
                    ['73', '7304', 'BPS KABUPATEN JENEPONTO'],
                    ['73', '7305', 'BPS KABUPATEN TAKALAR'],
                    ['73', '7306', 'BPS KABUPATEN GOWA'],
                    ['73', '7307', 'BPS KABUPATEN SINJAI'],
                    ['73', '7308', 'BPS KABUPATEN MAROS'],
                    ['73', '7309', 'BPS KABUPATEN PANGKAJENE DAN KEPULAUAN'],
                    ['73', '7310', 'BPS KABUPATEN BARRU'],
                    ['73', '7311', 'BPS KABUPATEN BONE'],
                    ['73', '7312', 'BPS KABUPATEN SOPPENG'],
                    ['73', '7313', 'BPS KABUPATEN WAJO'],
                    ['73', '7314', 'BPS KABUPATEN SIDENRENG RAPPANG'],
                    ['73', '7315', 'BPS KABUPATEN PINRANG'],
                    ['73', '7316', 'BPS KABUPATEN ENREKANG'],
                    ['73', '7317', 'BPS KABUPATEN LUWU'],
                    ['73', '7318', 'BPS KABUPATEN TANA TORAJA'],
                    ['73', '7322', 'BPS KABUPATEN LUWU UTARA'],
                    ['73', '7325', 'BPS KABUPATEN LUWU TIMUR'],
                    ['73', '7326', 'BPS KABUPATEN TORAJA UTARA'],
                    ['73', '7371', 'BPS KOTA MAKASSAR'],
                    ['73', '7372', 'BPS KOTA PAREPARE'],
                    ['73', '7373', 'BPS KOTA PALOPO'],
                    ['74', '7400', 'BPS PROVINSI SULAWESI TENGGARA'],
                    ['74', '7401', 'BPS KABUPATEN BUTON'],
                    ['74', '7402', 'BPS KABUPATEN MUNA'],
                    ['74', '7403', 'BPS KABUPATEN KONAWE'],
                    ['74', '7404', 'BPS KABUPATEN KOLAKA'],
                    ['74', '7405', 'BPS KABUPATEN KONAWE SELATAN'],
                    ['74', '7406', 'BPS KABUPATEN BOMBANA'],
                    ['74', '7407', 'BPS KABUPATEN WAKATOBI'],
                    ['74', '7408', 'BPS KABUPATEN KOLAKA UTARA'],
                    ['74', '7409', 'BPS KABUPATEN BUTON UTARA'],
                    ['74', '7410', 'BPS KABUPATEN KONAWE UTARA'],
                    ['74', '7411', 'BPS KABUPATEN KOLAKA TIMUR'],
                    ['74', '7471', 'BPS KOTA KENDARI'],
                    ['74', '7472', 'BPS KOTA BAUBAU'],
                    ['75', '7500', 'BPS PROVINSI GORONTALO'],
                    ['75', '7501', 'BPS KABUPATEN BOALEMO'],
                    ['75', '7502', 'BPS KABUPATEN GORONTALO'],
                    ['75', '7503', 'BPS KABUPATEN POHUWATO'],
                    ['75', '7504', 'BPS KABUPATEN BONE BOLANGO'],
                    ['75', '7505', 'BPS KABUPATEN GORONTALO UTARA'],
                    ['75', '7571', 'BPS KOTA GORONTALO'],
                    ['76', '7600', 'BPS PROVINSI SULAWESI BARAT'],
                    ['76', '7601', 'BPS KABUPATEN MAJENE'],
                    ['76', '7602', 'BPS KABUPATEN POLEWALI MANDAR'],
                    ['76', '7603', 'BPS KABUPATEN MAMASA'],
                    ['76', '7604', 'BPS KABUPATEN MAMUJU'],
                    ['76', '7605', 'BPS KABUPATEN MAMUJU UTARA/PASANGKAYU'],
                    ['81', '8100', 'BPS PROVINSI MALUKU'],
                    ['81', '8101', 'BPS KABUPATEN MALUKU TENGGARA BARAT/KEP. TANIMBAR'],
                    ['81', '8102', 'BPS KABUPATEN MALUKU TENGGARA'],
                    ['81', '8103', 'BPS KABUPATEN MALUKU TENGAH'],
                    ['81', '8104', 'BPS KABUPATEN BURU'],
                    ['81', '8105', 'BPS KABUPATEN KEPULAUAN ARU'],
                    ['81', '8106', 'BPS KABUPATEN SERAM BAGIAN BARAT'],
                    ['81', '8107', 'BPS KABUPATEN SERAM BAGIAN TIMUR'],
                    ['81', '8108', 'BPS KABUPATEN MALUKU BARAT DAYA'],
                    ['81', '8109', 'BPS KABUPATEN BURU SELATAN'],
                    ['81', '8171', 'BPS KOTA AMBON'],
                    ['82', '8200', 'BPS PROVINSI MALUKU UTARA'],
                    ['82', '8201', 'BPS KABUPATEN HALMAHERA BARAT'],
                    ['82', '8202', 'BPS KABUPATEN HALMAHERA TENGAH'],
                    ['82', '8203', 'BPS KABUPATEN KEPULAUAN SULA'],
                    ['82', '8204', 'BPS KABUPATEN HALMAHERA SELATAN'],
                    ['82', '8205', 'BPS KABUPATEN HALMAHERA UTARA'],
                    ['82', '8206', 'BPS KABUPATEN HALMAHERA TIMUR'],
                    ['82', '8207', 'BPS KABUPATEN PULAU MOROTAI'],
                    ['82', '8271', 'BPS KOTA TERNATE'],
                    ['82', '8272', 'BPS KOTA TIDORE KEPULAUAN'],
                    ['91', '9100', 'BPS PROVINSI PAPUA BARAT'],
                    ['91', '9101', 'BPS KABUPATEN FAKFAK'],
                    ['91', '9102', 'BPS KABUPATEN KAIMANA'],
                    ['91', '9103', 'BPS KABUPATEN TELUK WONDAMA'],
                    ['91', '9104', 'BPS KABUPATEN TELUK BINTUNI'],
                    ['91', '9105', 'BPS KABUPATEN MANOKWARI'],
                    ['91', '9106', 'BPS KABUPATEN SORONG SELATAN'],
                    ['91', '9107', 'BPS KABUPATEN SORONG'],
                    ['91', '9108', 'BPS KABUPATEN RAJA AMPAT'],
                    ['91', '9171', 'BPS KOTA SORONG'],
                    ['94', '9400', 'BPS PROVINSI PAPUA'],
                    ['94', '9401', 'BPS KABUPATEN MERAUKE'],
                    ['94', '9402', 'BPS KABUPATEN JAYAWIJAYA'],
                    ['94', '9403', 'BPS KABUPATEN JAYAPURA'],
                    ['94', '9404', 'BPS KABUPATEN NABIRE'],
                    ['94', '9408', 'BPS KABUPATEN KEPULAUAN YAPEN'],
                    ['94', '9409', 'BPS KABUPATEN BIAK NUMFOR'],
                    ['94', '9410', 'BPS KABUPATEN PANIAI'],
                    ['94', '9411', 'BPS KABUPATEN PUNCAK JAYA'],
                    ['94', '9412', 'BPS KABUPATEN MIMIKA'],
                    ['94', '9413', 'BPS KABUPATEN BOVEN DIGOEL'],
                    ['94', '9414', 'BPS KABUPATEN MAPPI'],
                    ['94', '9415', 'BPS KABUPATEN ASMAT'],
                    ['94', '9416', 'BPS KABUPATEN YAHUKIMO'],
                    ['94', '9417', 'BPS KABUPATEN PEGUNUNGAN BINTANG'],
                    ['94', '9418', 'BPS KABUPATEN TOLIKARA'],
                    ['94', '9419', 'BPS KABUPATEN SARMI'],
                    ['94', '9420', 'BPS KABUPATEN KEEROM'],
                    ['94', '9426', 'BPS KABUPATEN WAROPEN'],
                    ['94', '9427', 'BPS KABUPATEN SUPIORI'],
                    ['94', '9433', 'BPS KABUPATEN PUNCAK'],
                    ['94', '9471', 'BPS KOTA JAYAPURA'],
                    ['0', '21', 'Biro Perencanaan'],
                    ['0', '22', 'Biro Keuangan'],
                    ['0', '23', 'Biro Sumber Daya Manusia'],
                    ['0', '24', 'Biro Hubungan Masyarakat dan Hukum'],
                    ['0', '25', 'Biro Umum'],
                    ['0', '26', 'Pusat Pendidikan dan Pelatihan'],
                    ['0', '27', 'Politeknik Statistika STIS'],
                    ['0', '31', 'Direktorat Pengembangan Metodologi Sensus dan Survei'],
                    ['0', '32', 'Direktorat Diseminasi Statistik'],
                    ['0', '33', 'Direktorat Sistem Informasi Statistik'],
                    ['0', '41', 'Direktorat Statistik Kependudukan dan Ketenagakerjaan'],
                    ['0', '42', 'Direktorat Statistik Kesejahteraan Rakyat'],
                    ['0', '43', 'Direktorat Statistik Ketahanan Sosial'],
                    ['0', '51', 'Direktorat Statistik Tanaman Pangan, Hortikultura, dan Perkebunan'],
                    ['0', '52', 'Direktorat Statistik Peternakan, Perikanan, dan Kehutanan'],
                    ['0', '53', 'Direktorat Statistik Industri'],
                    ['0', '61', 'Direktorat Statistik Distribusi'],
                    ['0', '62', 'Direktorat Statistik Harga'],
                    ['0', '63', 'Direktorat Statistik Keuangan, Teknologi Informasi, dan Pariwisata'],
                    ['0', '71', 'Direktorat Neraca Produksi'],
                    ['0', '72', 'Direktorat Neraca Pengeluaran'],
                    ['0', '73', 'Direktorat Analisis dan Pengembangan Statistik'],
                    ['0', '81', 'Inspektorat Wilayah I'],
                    ['0', '82', 'Inspektorat Wilayah II'],
                    ['0', '83', 'Inspektorat Wilayah III'],
                    ['0', '20', 'Sekretariat Utama'],
                    ['0', '30', 'Kedeputian Bidang Metodologi dan Informasi Statistik'],
                    ['0', '40', 'Kedeputian Bidang Statistik Sosial'],
                    ['0', '50', 'Kedeputian Bidang Statistik Produksi'],
                    ['0', '60', 'Kedeputian Bidang Statistik Distribusi dan Jasa'],
                    ['0', '70', 'Kedeputian Bidang Neraca dan Analisis Statistik'],
                    ['0', '80', 'Inspektorat Utama'],
                    ['99', '9999', 'Badan Pemeriksa Keuangan'],
            ]
        ];

        foreach ($data as $unitData) {
            UnitKerja::factory()->create([
                'kode_wilayah' => $unitData[0],
                'kode_satker' => $unitData[1],
                'nama' => $unitData[2],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
